export const IMAGES_FETCH_START = "IMAGES_FETCH_START";
export const IMAGES_ADD = "IMAGES_ADD";
export const IMAGES_TOGGLE_SELECT = "IMAGES_TOGGLE_SELECT";
export const IMAGES_ROTATE_SELECTED = "IMAGES_ROTATE_SELECTED";
export const IMAGES_ROTATE_ALL = "IMAGES_ROTATE_ALL";
export const IMAGES_RESET_ROTATION = "IMAGES_RESET_ROTATION";